### ISSUE TITLE
Hills get sliced up by caves

### ISSUE THREAD

**Issue by anoomolu** [Tesseract4D/WorleyCaves#2]
Hiya. Thanks for bringing Worley's to 1.7.10, definitely one of my favourite cave overhauls ^^

I was wondering if you'd be able to fix a bug that is in this release (also present in the original).

![image](https://github.com/user-attachments/assets/95f2cc79-c74b-47ee-b458-f1684c0201f4)
![image](https://github.com/user-attachments/assets/93d6f8c8-48fd-4d5f-91f8-320681d5047a)

There are these slices or gaps in the terrain, especially visible on hills. It looks quite out of place, so any attempt at a fix would be greatly appreciated. Thank you.

**Comment by TesseractLHY** [comment]
It was fixed now,check [this](https://modrinth.com/mod/worleys-cave-legacy/version/1.5.4)

**Comment by TesseractLHY** [comment]
Sorry for the late.

**Comment by anoomolu** [comment]
No worries, thank you for the fix 💜
