### ISSUE TITLE
LOTR support.

### ISSUE THREAD

**Issue by MagmaSlime123** [Tesseract4D/WorleyCaves#3]
Title. Please let this mod's caves effect caves in the mod. I have also tried ImmersiveCaveGen and the GregCaves fork on Modrinth as well.

All 3 don't work. Something that does would be nice.

![2024-11-02_14 35 31](https://github.com/user-attachments/assets/4be2603a-2a9b-4599-9fde-020166020832)

**Comment by TesseractLHY** [comment]
What is LOTR?

**Comment by TesseractLHY** [comment]
Show me your mod list.

**Comment by MagmaSlime123** [comment]
> What is LOTR?

Lord of The Rings mod.

**Comment by MagmaSlime123** [comment]
> Show me your mod list.

Happens with any of these 3 mods if they're used with the Lord of The Rings mod. Even if nothing else is loaded.

**Comment by TesseractLHY** [comment]
![2024-11-07_23 26 05](https://github.com/user-attachments/assets/7827604c-4a5c-4e81-ae85-100773c9f9f8)

**Comment by TesseractLHY** [comment]
I think it is cracking a nut using a sledgehammer to create a mod for a small fix, so I made a mod specially designed for doing small fixes using javascript.

**Comment by TesseractLHY** [comment]
Install this [mod](https://github.com/Tesseract4D/DragonflyJS/releases/download/1.1/djs-1.0.jar),
[lotr_caves_compat.zip](https://github.com/user-attachments/files/17665436/lotr_caves_compat.zip)
Unzip this file then put the js file into djs directory.

**Comment by MagmaSlime123** [comment]
> Install this [mod](https://github.com/Tesseract4D/DragonflyJS/releases/download/1.1/djs-1.0.jar), [lotr_caves_compat.zip](https://github.com/user-attachments/files/17665436/lotr_caves_compat.zip) Unzip this file then put the js file into djs directory.

Could combine these into a mod and post this onto Modrinth.
